### ISSUE TITLE
Investigate a way install markdown-it plugins through UI

### ISSUE THREAD

**Issue by kolya-ay** [SAKryukov/vscode-extensible-markdown#2]
It should be possible at least through shell "npm install" call

**Comment by SAKryukov** [comment]
Thank you for your issue report.

Should it? I wonder, why?

This is not an npm module but is a Visual Studio Code (VSCode) Extension, which has its own mechanism for extension installation, which is done from withing the VSCode environment, or via [this product page](https://marketplace.visualstudio.com/items?itemName=sakryukov.convert-markdown-to-html). **Outside VSCode, this product has absolutely no value.** Moreover, it is not installed in the user's npm code base. Therefore, I don't see a reason for participation in npm. (I have other contribution related to markdown which does install by npm.)

Thank you.
—SA
