### ISSUE TITLE
markdown to html stopped working in VS Code

### ISSUE THREAD

**Issue by pfister** [SAKryukov/vscode-extensible-markdown#3]
When I right click and attempt "Markdown: Convert to &Html" nothing happens. An html file is not created.

If I shift+ctrl+P, and select "Markdown: Convert to &Html" command, again an html file is not created. However, I can see an error message in lower right corner of markdown edit window that says:
 >"X Command 'extensible.markdown.convertToHtml' not found"

Please fix!

**Comment by pitjupp** [comment]
To this issue I worked out, that it is broken with vscode version 1.21.
When I downgrade vscode to 1.20.1 the extension works correctly. So it seems, the incorrect behaviour started with version 1.21 of vscode.

I hope, this may help to find the trouble.

**Comment by geoffyuen** [comment]
This extension is still not working with VSCode 1.24.1.

**Comment by andresmoschini** [comment]
Still not working with VSCode 1.28.2 on Mac

**Comment by kulkarniamit** [comment]
Still not working on Ubuntu 14 :
```
Version: 1.29.1
Commit: bc24f98b5f70467bc689abf41cc5550ca637088e
Date: 2018-11-15T19:07:43.495Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64
```

Error at the bottom right of screen:
`command 'extensible.markdown.convertToHtml' not found`

**Comment by ghost** [comment]
Unfortunately, VSCode lost extension API compatibility with the earlier versions when the extension.
I'll have to review entire code to make it working.

**Comment by SAKryukov** [comment]
Fully resolved, new version basically works but is under development, with new features, such as block element attributes, abbreviations and extra replacements.
